name: Docker Compose Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start Docker Compose
        run: |
          docker compose -f docker-compose.yml up --build -d
          docker network inspect bridge | grep express-vue-app || docker network connect bridge express-vue-app

      - name: Wait for services to be healthy
        run: |
          sleep 30 # Adjust this based on your services' startup time

      - name: Test application health
        run: |
          docker exec express-vue-app curl -f http://localhost:3000 || exit 1

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker compose -f docker-compose.yml down
